### ISSUE TITLE
Reserva: Integrar con hotel de la sesión

### ISSUE THREAD

**Issue by bstolarz** [jbmild/WHERE_EN_EL_DELETE_FROM#13]
si no es guest (es usuario): solo dejarlo reservar, modificar y eliminar reservas del hotel logueado.
Si es guest le sigo mostrando el combo con todos los hoteles

**Comment by jbmild** [comment]
Para validar si es o no guest alcanza con Validar de Sesión.hotel q este en
null

**Comment by bstolarz** [comment]
Hecho
