### ISSUE TITLE
ABM Regimen Estadia - agregarlo a Pantalla principal con popup

### ISSUE THREAD

**Issue by bstolarz** [jbmild/WHERE_EN_EL_DELETE_FROM#4]
EL TP pide que no se desarrolle el ABM de Regimen, entiendo que habría que sacarlo.
No es urgente obvio, pero lo dejo asentado para que tengamos algo menos :)

**Comment by bstolarz** [comment]
@juanmacaru @fpatalagoity

**Comment by jbmild** [comment]
Ya estaba hecho? Si te referis a borrarlo de la DB eso no hay q hacerlo.
Tiene q estar en la DB y los modelos q hagamos.

**Comment by bstolarz** [comment]
Me refiero a la solución de C#. De ahi habria que sacarlo porque el TP dice que no hay que desarrollarlo.
@jbmild
