### ISSUE TITLE
ABM Habitación - falta campo Tipo Habitación

### ISSUE THREAD

**Issue by bstolarz** [jbmild/WHERE_EN_EL_DELETE_FROM#8]
En las pantallas de alta y modificación y listados no está el campo Tipo Habitación.

**Comment by fpatalagoity** [comment]
En listado ya está. Sigo con alta @bstolarz

**Comment by fpatalagoity** [comment]
El tipo de habitación no es modificable en la modificación según el enunciado:
Todos los datos mencionados anteriormente son modificables, excepto el tipo de
habitación a fin de simplificar el desarrollo
